name: Heroku workflow

on:
  push:
    branches: [master, develop]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: set up node
        uses: actions/setup-node@v2
        working-directory: backend
        with:
          node-version: "14"

      - name: checkout code
        uses: actions/checkout@v2
        working-directory: backend

      - name: setup cache
        uses: actions/cache@v1
        working-directory: backend
        with:
          path: ~/.npm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-modules-
            ${{ runner.os }}-

      - name: install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm test

      - name: build
        run: npm run build

      - name: build docker image
        run: docker build . -t simona87/library-backend

      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: simona87/library-backend

      - name: login to heroku
        run: heroku container:login
        env:
          HEROKU_API_KEY:
