name: Heroku workflow

on:
  push:
    branches: [main, develop]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: checkout code
        uses: actions/checkout@v2

      - name: setup cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-modules-
            ${{ runner.os }}-

      - name: install
        run: npm ci
        working-directory: backend

      - name: lint
        run: npm run lint
        working-directory: backend

      - name: test
        run: npm test
        working-directory: backend

      - name: build
        run: npm run build
        working-directory: backend

      - name: build docker image
        run: docker build ./backend -t simona87/library-backend

      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: simona87/library-backend

      - name: login to heroku
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: push to heroku
        run: heroku container:push -a app-simona-library --recursive
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        working-directory: backend

      - name: release the image
        run: docker container:release -a app-simona-library --recursive
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        working-directory: backend
